language: python
python:
  - "2.7"
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: xYPP/moV+KaDjibxyYxAe1cqRyo5IFmJ7jjN0zBMx/iQQ/W8UszenuguXuNflXz+L9osLpLGFDL1MQDayHLInSUPT7oBjuz9gMgTqcgyr5M3vC6sAhITWF+8pEzrLN1ugzcw1Puk0QSh8gntUGA7BwsJIf/XDUtL6fasUXiADAiZIxBOCLlO8IrkgT83QR7cfZoT7AlOVemEq2IuNYDydXy7Oz7613nTelyPt6buTyJjBdfZuvYhNShd8sjDgVFNibDcZuHJEfGuxE92EnoRu4Af6z35vTGeFkQIQnzHI9MhfLphiaBjrAIg5dFYg6V3zA9S8N37NcvS+Q3Djq1/83bYHkBUqvCCEn9290f4J8jISlwtx4FaRonxcx5bR51/UmCc9GO6ErCBvpG5y+k8F1ltED/lQjVRaIntFHB7DvfQ5Yo3yNVG79adT7cI9VcTL7mCpdynyfX26QctjWo+3emffmhNK9s5yGS9a0KiE7LoBUHnh2lT9+sgcH+6GdeopwGu6VjfBV1cAU9hA+2VKZK3owlI+RRSdQh0T+3aJORaqqY65hRm7fe79jN4HMBpZYAVvYekBzcPBqQ/024C2eK/pPtaAYnNav7dOwG2u41KcJXPq1tP3a0FSKrkufZDZfP8KAIdM8MBjMC4wyrQ58fSa4JsmdBZloXHEhqNp+Q=
